//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public int MusicAuthorID { get; set; }
        public int TextAuthorID { get; set; }
        public string SongName { get; set; }
        public string PathToSong { get; set; }
        public string SongNotes { get; set; }
        public string PathToText { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Author Author { get; set; }
        public virtual Author Author1 { get; set; }
    }
}
