//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.SongAccords = new HashSet<SongAccord>();
        }
    
        public int SongID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public int MusicAuthorID { get; set; }
        public int TextAuthorID { get; set; }
        public string SongName { get; set; }
        public string PathToSong { get; set; }
        public string SongNotes { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Author Author { get; set; }
        public virtual Author Author1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongAccord> SongAccords { get; set; }
    }
}
