//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongAccord
    {
        public int SongAccordID { get; set; }
        public Nullable<int> SongID { get; set; }
        public string SongAccordText { get; set; }
        public string SongAccordNotes { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
